# Generated by Django 5.0.2 on 2025-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rooms', models.IntegerField(default=0, verbose_name='Shifoxona xonalari')),
                ('doctors', models.IntegerField(default=0, verbose_name='Mutaxassis doktorlar')),
                ('patients', models.IntegerField(default=0, verbose_name='Mamnun bemorlar')),
                ('experience', models.IntegerField(default=0, verbose_name='Yillik tajriba')),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
