# Generated by Django 5.0.2 on 2025-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Xona nomi')),
                ('room_number', models.CharField(max_length=20, verbose_name='Xona raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
            ],
            options={
                'verbose_name': 'Klinika xonasi',
                'verbose_name_plural': 'Klinika xonalari',
                'ordering': ['room_number'],
            },
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
