# Generated by Django 5.0.2 on 2025-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', 'queue_number'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqti'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_patient',
            field=models.BooleanField(default=False, verbose_name='Bemor tomonidan bekor qilingan'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqti'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(verbose_name='Navbat sanasi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Eslatmalar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(verbose_name='Navbat raqami'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilayotgan'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
