# Generated by Django 5.0.2 on 2025-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram ID')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Telegram State',
                'verbose_name_plural': 'Telegram States',
                'ordering': ['-created_at'],
            },
        ),
    ]
